/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emp;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author RUHANLI
 */
public class GUI extends javax.swing.JFrame {

    final private int k = 5;
    final private HashTable database = new HashTable(k);
    private boolean empFull = true;
    int tempNumber;
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        database.read(database); 
        empType.setSelectedIndex(0);
        wagePerWeek.setEditable(false);
        editEmp.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        addEmp = new javax.swing.JButton();
        remEmp = new javax.swing.JButton();
        editEmp = new javax.swing.JButton();
        fNameBox = new javax.swing.JTextField();
        lNameBox = new javax.swing.JTextField();
        dedRateBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        empWage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        empType = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        empNum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        viewEmp = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        hoursPerWeek = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        wagePerWeek = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        calcWage = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                GUI.this.windowClosing(evt);
            }
        });

        addEmp.setText("Add Employee");
        addEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpActionPerformed(evt);
            }
        });

        remEmp.setText("Remove Emp.");
        remEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remEmpActionPerformed(evt);
            }
        });

        editEmp.setText("Edit Employee");
        editEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmpActionPerformed(evt);
            }
        });

        fNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameBoxActionPerformed(evt);
            }
        });

        dedRateBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dedRateBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("Deduction Rate (.)");

        empWage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empWageActionPerformed(evt);
            }
        });

        jLabel5.setText("Salary ($)");

        empType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Full Time", "Part Time" }));
        empType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empTypeActionPerformed(evt);
            }
        });

        jLabel6.setText("Employee Type");

        empNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNumActionPerformed(evt);
            }
        });

        jLabel7.setText("Employee #");

        viewEmp.setText("View Database");
        viewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmpActionPerformed(evt);
            }
        });

        jLabel8.setText("Hours per week");

        hoursPerWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursPerWeekActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Employee Number:");

        jButton1.setText("Save Database");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        wagePerWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wagePerWeekActionPerformed(evt);
            }
        });

        jLabel11.setText("Amount Earned ($)");

        calcWage.setText("Calculate Yearly Wage");
        calcWage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcWageActionPerformed(evt);
            }
        });

        jButton2.setText("Clear Fields");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("EMPLOYEE DATABASE - RAYMOND LI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wagePerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calcWage, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(editEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(remEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel10))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empNum, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empWage, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(lNameBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(dedRateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewEmp)
                                    .addComponent(jButton1))))
                        .addGap(24, 24, 24))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(viewEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addEmp)
                            .addComponent(dedRateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(33, 33, 33)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(editEmp)
                                    .addComponent(remEmp))
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calcWage)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(wagePerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmpActionPerformed
        if (editEmp.getBackground() == Color.WHITE) {
        try {
                Employee exist = database.getEmployee(Integer.parseInt(jTextField1.getText()));
                tempNumber = Integer.parseInt(jTextField1.getText());
                if (exist != null) {
                    if (exist instanceof FullTimeEmployee) {
                        empType.setSelectedIndex(0);
                        empNum.setText(Integer.toString(exist.getEmpNumber()));
                        fNameBox.setText(exist.getFirstName());
                        lNameBox.setText(exist.getLastName());
                        dedRateBox.setText(Float.toString(exist.getDedRate()));
                        empWage.setText(Float.toString(((FullTimeEmployee) exist).getSalary()));
                    } else if (exist instanceof PartTimeEmployee) {
                        empType.setSelectedIndex(1);
                        empNum.setText(Integer.toString(exist.getEmpNumber()));
                        fNameBox.setText(exist.getFirstName());
                        lNameBox.setText(exist.getLastName());
                        dedRateBox.setText(Float.toString(exist.getDedRate()));
                        empWage.setText(Float.toString(((PartTimeEmployee) exist).getHWage()));
                        hoursPerWeek.setText(Float.toString(((PartTimeEmployee) exist).getHPWeek()));
                        wagePerWeek.setText(Float.toString(exist.calcWeekPay()));
                    }
                    editEmp.setText("Confirm changes"); 
                    editEmp.setBackground(Color.gray);   
                } else {
                    JOptionPane.showMessageDialog(null, "Employee " + jTextField1.getText() + " isn't in the database.");
                jTextField1.setText("");
                }
                
            } catch (NumberFormatException a) {
                JOptionPane.showMessageDialog(null, "Error.");
               
            }
    }//GEN-LAST:event_editEmpActionPerformed
        else if (editEmp.getBackground() == Color.GRAY) {
            if (empType.getSelectedItem().toString().equals("Full Time")) {
                empFull = true;
                if (empFull == true) {
                    FullTimeEmployee tempEmp = new FullTimeEmployee (Integer.parseInt(empNum.getText()), fNameBox.getText(), lNameBox.getText(),Float.parseFloat(dedRateBox.getText()),Float.parseFloat(empWage.getText()));
                        database.removeEmployee(tempNumber);
                        database.addEmployee(tempEmp);
                        empNum.setText("");
                        dedRateBox.setText("");
                        fNameBox.setText("");
                        lNameBox.setText("");
                        empWage.setText("");
                                editEmp.setBackground(Color.WHITE);
            }
                JOptionPane.showMessageDialog(null, "Changes have been made");
                editEmp.setText("Edit Employee");
        }
        
        else {
                    //Performs same operations as Full Time but for Part Time, also uses the weekly hours text field
                    PartTimeEmployee tempEmp = new PartTimeEmployee (Integer.parseInt(empNum.getText()), fNameBox.getText(), lNameBox.getText(),Float.parseFloat(dedRateBox.getText()),Float.parseFloat(empWage.getText()),Float.parseFloat(hoursPerWeek.getText()) );
                        database.removeEmployee(tempNumber);
                        database.addEmployee(tempEmp);
                        empNum.setText("");
                        dedRateBox.setText("");
                        fNameBox.setText("");
                        lNameBox.setText("");
                        empWage.setText("");
                                editEmp.setBackground(Color.WHITE);
    }
}
    }
    private void addEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpActionPerformed
        try {
            if (empFull == true) {
                boolean exists = database.searching(Integer.parseInt(empNum.getText()));
                FullTimeEmployee tempEmp = new FullTimeEmployee (Integer.parseInt(empNum.getText()), fNameBox.getText(), lNameBox.getText(),Float.parseFloat(dedRateBox.getText()),Float.parseFloat(empWage.getText()));
                if (tempEmp.calcWeekPay() > 0 && exists == false){
                     database.addEmployee(tempEmp);
                     fNameBox.setText("");
                     lNameBox.setText("");
                     empNum.setText("");
                     dedRateBox.setText("");
                     empWage.setText("");  
                } else if (tempEmp.calcWeekPay() <= 0) {
                        JOptionPane.showMessageDialog(null, "Error");
                } else if (exists == true) {
                        JOptionPane.showMessageDialog(null, "Employee already exists.");
                }
            } else if (empFull == false) {
                PartTimeEmployee tempEmp = new PartTimeEmployee (Integer.parseInt(empNum.getText()), fNameBox.getText(), lNameBox.getText(),Float.parseFloat(dedRateBox.getText()),Float.parseFloat(empWage.getText()),Float.parseFloat(hoursPerWeek.getText()) );
                boolean exists = database.searching(Integer.parseInt(empNum.getText()));    
                if (tempEmp.calcWeekPay() > 0 && exists == false) {
                    database.addEmployee(tempEmp);
                    fNameBox.setText("");
                    lNameBox.setText("");
                    empNum.setText("");
                    dedRateBox.setText("");
                    empWage.setText("");  
                   
                } else if (tempEmp.calcWeekPay() <= 0) {
                    JOptionPane.showMessageDialog(null, "Employees must have a positive weekly pay.");
                } else if (exists == true) {
                    JOptionPane.showMessageDialog(null, "Employee already exists in the database.");
                
                } 
}//GEN-LAST:event_addEmpActionPerformed
        } catch (NumberFormatException a) {
            JOptionPane.showMessageDialog(null, "ERROR.");
        }
    }

    private void fNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameBoxActionPerformed

    private void empNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empNumActionPerformed

    private void empWageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empWageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empWageActionPerformed

    private void empTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empTypeActionPerformed
        if (empType.getSelectedItem().toString().equals("Full Time")) {
            fNameBox.setText("");
            lNameBox.setText("");
            empNum.setText("");
            dedRateBox.setText("");
            empWage.setText(""); 
            jLabel8.setVisible(false);
            hoursPerWeek.setVisible(false);
            //Stores state of combo box
            empFull = true;
            //Same process for Part Time
        } else if (empType.getSelectedItem().toString().equals("Part Time")) {
            fNameBox.setText("");
            lNameBox.setText("");
            empNum.setText("");
            dedRateBox.setText("");
            empWage.setText(""); 
            jLabel8.setVisible(true);
            hoursPerWeek.setVisible(true);
            empFull = false;
        }
    }//GEN-LAST:event_empTypeActionPerformed

    private void dedRateBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dedRateBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dedRateBoxActionPerformed

    private void hoursPerWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursPerWeekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursPerWeekActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        database.save();      
        JOptionPane.showMessageDialog(null, "Your changes have been saved.");
            //Sorts the database before storing it in the text file
                  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmpActionPerformed
        database.display();
    }//GEN-LAST:event_viewEmpActionPerformed

    private void remEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remEmpActionPerformed
        try {
                Employee tempEmp = database.removeEmployee(Integer.valueOf(jTextField1.getText()));
                String emp = Integer.toString (Integer.valueOf(jTextField1.getText()));
                JOptionPane.showMessageDialog(null, "Employee " + emp + " has been removed!");
                if (tempEmp == null) {
                    JOptionPane.showMessageDialog(null, "Employee " + jTextField1.getText() + " isn't in the database.");
                }
                jTextField1.setText("");
            } catch (NumberFormatException a) {
                JOptionPane.showMessageDialog(null, "ERROR.");
                jTextField1.setText("");
            }
    }//GEN-LAST:event_remEmpActionPerformed

    private void calcWageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcWageActionPerformed
        try {
                Employee exist = database.getEmployee(Integer.parseInt(jTextField1.getText()));
                if (exist != null) {
                    if (exist instanceof FullTimeEmployee) {
                        wagePerWeek.setText(Float.toString(((FullTimeEmployee) exist).getSalary()));
                    } else if (exist instanceof PartTimeEmployee) {
                        wagePerWeek.setText(Float.toString(((PartTimeEmployee) exist).calcYearPay()));
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Employee " + jTextField1.getText() + " isn't in the database.");
                jTextField1.setText("");
                wagePerWeek.setText("");
                }
                
            } catch (NumberFormatException a) {
                JOptionPane.showMessageDialog(null, "Error.");
    }//GEN-LAST:event_calcWageActionPerformed
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            fNameBox.setText("");
            lNameBox.setText("");
            empNum.setText("");
            dedRateBox.setText("");
            empWage.setText(""); 
            hoursPerWeek.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void windowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosing
           
        int temp;
        //Creates the current state of the database
       
            temp = JOptionPane.showConfirmDialog(null, "Would you like to save?", "Save?", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            //If they enter yes, it will perform the same methods as the Save button
            if (temp == 0) {
                database.save();
                JOptionPane.showMessageDialog(null, "Your changes have been saved!");
            } else {
                JOptionPane.showMessageDialog(null, "Your changes have not been saved!");

    }
    }//GEN-LAST:event_windowClosing

    private void wagePerWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wagePerWeekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wagePerWeekActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmp;
    private javax.swing.JButton calcWage;
    private javax.swing.JTextField dedRateBox;
    private javax.swing.JButton editEmp;
    private javax.swing.JTextField empNum;
    private javax.swing.JComboBox empType;
    private javax.swing.JTextField empWage;
    private javax.swing.JTextField fNameBox;
    private javax.swing.JTextField hoursPerWeek;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField lNameBox;
    private javax.swing.JButton remEmp;
    private javax.swing.JButton viewEmp;
    private javax.swing.JTextField wagePerWeek;
    // End of variables declaration//GEN-END:variables
}
